sudo: false
language: ruby
rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4
before_install: gem install bundler

services:
  - postgresql

before_script:
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml

script:
  - cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:schema:load && cd ../..
  - bundle exec rspec
